version: "3.8"
services:
  database-go-parser:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data